Repository SinguloStation13/SinguloStation-Red, pull requests merged in 2021-08, with the labels that each got.

#91 [MIRROR] Fix some CRLF json files
  TGS3.json
  _maps/boxstation.json
  _maps/multiz_debug.json
  _maps/runtimestation.json
Labels: mapping

#92 [MIRROR] FIXES HEARING FOR THE 17TH TIME
  TGS3.json
  _maps/boxstation.json
  _maps/multiz_debug.json
  _maps/runtimestation.json
  code/game/machinery/Sleeper.dm
  code/game/machinery/harvester.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/pet_carrier.dm
  code/game/turfs/open/lava.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/spells/spell_types/shapeshift.dm
Labels: mapping

#100 [MIRROR] [PORT] EVEN MORE HARDDEL FIXES
  code/_onclick/observer.dm
  code/controllers/subsystem/throwing.dm
  code/datums/brain_damage/split_personality.dm
  code/datums/components/chasm.dm
  code/datums/holocall.dm
  code/datums/mutations/antenna.dm
  code/datums/status_effects/status_effect.dm
  code/game/atoms_movable.dm
  code/game/communications.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/motion.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/computer/teleporter.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/hologram.dm
  code/game/machinery/teleporter.dm
  code/game/objects/items/devices/camera_bug.dm
  code/game/objects/items/implants/implant_misc.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/tanks/tanks.dm
  code/game/objects/items/teleportation.dm
  code/game/objects/objs.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/turf.dm
  code/modules/admin/verbs/diagnostics.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  code/modules/atmospherics/machinery/components/unary_devices/heat_exchanger.dm
  code/modules/buildmode/buildmode.dm
  code/modules/detectivework/detective_work.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/plumbing/ducts.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/station_goals/bsa.dm
  code/modules/tgui/tgui.dm
Labels: Administration

#86 [MIRROR] New bans default to global
  code/modules/admin/sql_ban_system.dm
Labels: Administration

#115 [MIRROR] Shameless self-insert
  sound/voice/lizard/credits.txt
Labels: sound

#120 [MIRROR] Juke Build Reforged
  .dockerignore
  .editorconfig
  .github/workflows/continuous_integration.yml
  .gitignore
  .tgs4.yml
  .vscode/launch.json
  .vscode/tasks.json
  BUILD.bat
  Dockerfile
  README.md
  code/_compile_options.dm
  code/modules/asset_cache/asset_list_items.dm
  dependencies.sh
  tgui/.gitignore
  tgui/bin/tgui
  tgui/packages/tgfont/dist/tgfont.css
  tgui/packages/tgfont/dist/tgfont.eot
  tgui/packages/tgfont/dist/tgfont.woff2
  tgui/public/tgui-common.bundle.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  tools/bootstrap/node
  tools/bootstrap/node.bat
  tools/bootstrap/node_.ps1
  tools/build/.editorconfig
  tools/build/README.md
  tools/build/build
  tools/build/build.bat
  tools/build/build.js
  tools/build/cbt/dm.js
  tools/build/cbt/fs.js
  tools/build/cbt/winreg.js
  tools/build/cbt/yarn.js
  tools/build/juke/index.d.ts
  tools/build/juke/index.js
  tools/ci/build.ps1
  tools/ci/build_tgui.sh
  tools/ci/dm.sh
  tools/ci/install_build_tools.sh
  tools/ci/install_node.sh
  tools/ci/run_server.sh
  tools/deploy.sh
  tools/linux_build.py
  tools/tgs4_scripts/PreCompile.sh
  yarn.lock
Labels: GitHub, TGUI-Changes, tools
